name: Daily Payroll Brief

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run daily brief
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_MODEL: ${{ secrets.ANTHROPIC_MODEL }}
          KWORK_APP_KEY: ${{ secrets.KWORK_APP_KEY }}
          KWORK_TO_EMAIL: ${{ secrets.KWORK_TO_EMAIL }}
          KWORK_CONVERSATION_ID: ${{ secrets.KWORK_CONVERSATION_ID }}
        run: node dist/index.js
