name: Daily News Collection

on:
  schedule:
    # 매일 오전 6시 (한국시간) 실행
    - cron: '0 21 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  collect-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run news collection
        env:
          KWORK_APP_KEY: ${{ secrets.KWORK_APP_KEY }}
          KWORK_TO_EMAIL: ${{ secrets.KWORK_TO_EMAIL }}
          KWORK_CONVERSATION_ID: ${{ secrets.KWORK_CONVERSATION_ID }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: npm run dev
